### ISSUE TITLE
Checkout conflict with files

### ISSUE THREAD

**Issue by maxim-ge** [scm4j/scm4j-releaser#28]
Must be automatically handled somehow

```
`release branch version calculation: com.triniforce.tf-server-toolkit:tf-server-toolkit in 3204ms
status calculation: com.triniforce.tf-server-toolkit:tf-server-toolkit in 922ms
org.scm4j.vcs.api.exceptions.EVCSException: org.eclipse.jgit.api.errors.CheckoutConflictException: Checkout conflict with files: 
src/com/triniforce/soap/ClassParser.java
src/com/triniforce/soap/CustomSerializer.java
src/com/triniforce/soap/InterfaceDescriptionGenerator.java
src/com/triniforce/soap/SOAPServlet.java
src/com/triniforce/soap/TypeDefLibCache.java
test/com/triniforce/soap/ClassDefLibTest.java
test/com/triniforce/soap/ClassParserTest.java
test/com/triniforce/soap/CustomSerializerTest.java
test/com/triniforce/soap/InterfaceDescriptionGeneratorTest.java
test/com/triniforce/soap/ObjectConverterTest.java
test/com/triniforce/soap/SoapHandlerTest.java
test/com/triniforce/soap/TypeDefLibCacheTest.java
test/com/triniforce/soap/WsdlTypeElementTest.java
	at org.scm4j.vcs.GitVCS.fileExists(GitVCS.java:715)
	at org.scm4j.releaser.branch.DevelopBranch.getMDeps(DevelopBranch.java:57)
	at org.scm4j.releaser.SCMReleaser.lambda$getCalculatedResult$4(SCMReleaser.java:107)
	at org.scm4j.releaser.SCMReleaser.reportDuration(SCMReleaser.java:118)
	at org.scm4j.releaser.SCMReleaser.getCalculatedResult(SCMReleaser.java:107)
	at org.scm4j.releaser.SCMReleaser.getActionTree(SCMReleaser.java:52)
	at org.scm4j.releaser.SCMReleaser.getActionTree(SCMReleaser.java:47)
	at org.scm4j.releaser.SCMReleaser.getActionTree(SCMReleaser.java:35)
	at org.scm4j.releaser.SCMReleaser.getActionTree(SCMReleaser.java:31)
	at org.scm4j.releaser.cli.CLI.execInternal(CLI.java:59)
	at org.scm4j.releaser.cli.CLI.exec(CLI.java:76)
	at org.scm4j.releaser.cli.CLI.exec(CLI.java:89)
	at org.scm4j.releaser.cli.CLI$exec.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at CLIRunner.main(releaser.gsh:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1446)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:899)
	at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:287)
	at groovy.lang.GroovyShell.run(GroovyShell.java:518)
	at groovy.lang.GroovyShell.run(GroovyShell.java:507)
	at groovy.ui.GroovyMain.processOnce(GroovyMain.java:653)
	at groovy.ui.GroovyMain.run(GroovyMain.java:384)
	at groovy.ui.GroovyMain.process(GroovyMain.java:370)
	at groovy.ui.GroovyMain.processArgs(GroovyMain.java:129)
	at groovy.ui.GroovyMain.main(GroovyMain.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:109)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:131)
Caused by: org.eclipse.jgit.api.errors.CheckoutConflictException: Checkout conflict with files: 
src/com/triniforce/soap/ClassParser.java
src/com/triniforce/soap/CustomSerializer.java
src/com/triniforce/soap/InterfaceDescriptionGenerator.java
src/com/triniforce/soap/SOAPServlet.java
src/com/triniforce/soap/TypeDefLibCache.java
test/com/triniforce/soap/ClassDefLibTest.java
test/com/triniforce/soap/ClassParserTest.java
test/com/triniforce/soap/CustomSerializerTest.java
test/com/triniforce/soap/InterfaceDescriptionGeneratorTest.java
test/com/triniforce/soap/ObjectConverterTest.java
test/com/triniforce/soap/SoapHandlerTest.java
test/com/triniforce/soap/TypeDefLibCacheTest.java
test/com/triniforce/soap/WsdlTypeElementTest.java
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:275)
	at org.scm4j.vcs.GitVCS.checkout(GitVCS.java:387)
	at org.scm4j.vcs.GitVCS.fileExists(GitVCS.java:711)
	... 38 more
Caused by: org.eclipse.jgit.errors.CheckoutConflictException: Checkout conflict with files: 
src/com/triniforce/soap/ClassParser.java
src/com/triniforce/soap/CustomSerializer.java
src/com/triniforce/soap/InterfaceDescriptionGenerator.java
src/com/triniforce/soap/SOAPServlet.java
src/com/triniforce/soap/TypeDefLibCache.java
test/com/triniforce/soap/ClassDefLibTest.java
test/com/triniforce/soap/ClassParserTest.java
test/com/triniforce/soap/CustomSerializerTest.java
test/com/triniforce/soap/InterfaceDescriptionGeneratorTest.java
test/com/triniforce/soap/ObjectConverterTest.java
test/com/triniforce/soap/SoapHandlerTest.java
test/com/triniforce/soap/TypeDefLibCacheTest.java
test/com/triniforce/soap/WsdlTypeElementTest.java
	at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:448)
	at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:430)
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:271)
	... 40 more
```

**Comment by host6** [comment]
Happens when component's url has changed. To fix: delete folder $user.home/.scm4j/releaser-vcs-workspaces
